### ISSUE TITLE
minor refactoring

### ISSUE THREAD

**Issue by Izelude** [rosenbach/FungiJournal#29]
https://github.com/rosenbach/FungiJournal/blob/94a1db6c382d2a24ce019a51f74d5b8aa5fa2615/FungiJournal.DataAccess/CodeFirstDbContext.cs#L36

consider extracting methods instead of declaring regions.

`private void BuildFungiModel(ModelBuilder modelBuilder)`
`private void BuildSeasonalityInformationModel(ModelBuilder modelBuilder)`
etc.

**Comment by rosenbach** [comment]
fixed in PR #28
